INSERT INTO tbl_collections (collectionSetName, releaseDate, totalCardsInCollection) VALUES
    ('Base Set', '1999-01-09', 102),
    ('Jungle', '1999-06-16', 64),
    ('Fossil', '1999-10-10', 62),
    ('Team Rocket', '2000-04-24', 83),
    ('Gym Heroes', '2000-08-14', 132),
    ('Sword & Shield', '2020-02-07', 202),
    ('Scarlet & Violet', '2023-03-31', 198);

INSERT INTO tbl_cards (hp, name, type_id, stage_id, info, attack, damage, weakness, resistance, retreat, cardNumberInCollection, collection_id) VALUES
    (60, 'Pikachu', 4, 1, 'When several of these Pokemon gather, their electricity could build and cause lightning storms.', 'Thundershock', '10', 'Fighting ×2', NULL, 1, 58, 1),
    (120, 'Raichu', 4, 2, 'Its long tail serves as a ground to protect itself from its own high voltage power.', 'Thunder', '60', 'Fighting ×2', NULL, 1, 14, 1),
    (40, 'Charmander', 2, 1, 'Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.', 'Scratch', '10', 'Water ×2', NULL, 1, 46, 1),
    (80, 'Charmeleon', 2, 2, 'When it swings its burning tail, it elevates the temperature to unbearably high levels.', 'Slash', '30', 'Water ×2', NULL, 1, 24, 1),
    (150, 'Charizard', 2, 3, 'Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.', 'Fire Spin', '100', 'Water ×2', NULL, 3, 4, 1),
    (40, 'Squirtle', 3, 1, 'After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.', 'Bubble', '10', 'Lightning ×2', NULL, 1, 63, 1),
    (80, 'Wartortle', 3, 2, 'Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.', 'Bite', '40', 'Lightning ×2', NULL, 1, 42, 1),
    (140, 'Blastoise', 3, 3, 'A brutal Pokemon with pressurized water jets on its shell. They are used for high speed tackles.', 'Hydro Pump', '40+', 'Lightning ×2', NULL, 3, 2, 1),
    (50, 'Bulbasaur', 1, 1, 'A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokemon.', 'Leech Seed', '20', 'Fire ×2', NULL, 1, 44, 1),
    (60, 'Ivysaur', 1, 2, 'When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.', 'Vine Whip', '30', 'Fire ×2', NULL, 1, 30, 1),
    (140, 'Venusaur', 1, 3, 'The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.', 'Solar Beam', '60', 'Fire ×2', NULL, 2, 15, 1),
    (50, 'Meowth', 11, 1, 'Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change.', 'Pay Day', '10', 'Fighting ×2', NULL, 1, 56, 1),
    (60, 'Persian', 11, 2, 'Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness.', 'Slash', '30', 'Fighting ×2', NULL, 0, 42, 1),
    (60, 'Psyduck', 3, 1, 'While lulling its enemies with its vacant look, this wily Pokemon will use psychokinetic powers.', 'Headache', '20', 'Lightning ×2', NULL, 1, 54, 1),
    (80, 'Golduck', 3, 2, 'Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa.', 'Hyper Beam', '50', 'Lightning ×2', NULL, 1, 35, 1),
    (50, 'Machop', 6, 1, 'Loves to build its muscles. It trains in all styles of martial arts to become even stronger.', 'Low Kick', '20', 'Psychic ×2', NULL, 1, 52, 1),
    (80, 'Machoke', 6, 2, 'Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions.', 'Karate Chop', '50', 'Psychic ×2', NULL, 2, 34, 1),
    (120, 'Machamp', 6, 3, 'Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon.', 'Seismic Toss', '60', 'Psychic ×2', NULL, 2, 8, 1),
    (50, 'Abra', 5, 1, 'Using its ability to read minds, it will identify impending danger and teleport to safety.', 'Psyshock', '10', 'Psychic ×2', NULL, 1, 43, 2),
    (90, 'Kadabra', 5, 2, 'It emits special alpha waves from its body that induce headaches just by being close by.', 'Super Psy', '50', 'Psychic ×2', NULL, 2, 32, 2),
    (80, 'Alakazam', 5, 3, 'Its brain can outperform a supercomputer. Its intelligence quotient is said to be 5000.', 'Damage Swap', '0', 'Psychic ×2', NULL, 3, 1, 2),
    (60, 'Geodude', 6, 1, 'Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.', 'Stone Barrage', '10×', 'Grass ×2', NULL, 1, 47, 2),
    (80, 'Graveler', 6, 2, 'Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.', 'Rock Throw', '40', 'Grass ×2', NULL, 2, 37, 2),
    (120, 'Golem', 6, 3, 'Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.', 'Avalanche', '60', 'Grass ×2', NULL, 3, 36, 2),
    (40, 'Magnemite', 4, 1, 'Uses anti-gravity to stay suspended. Appears without warning and uses Thunder Wave and similar moves.', 'Thunder Wave', '10', 'Fighting ×2', 'Metal -30', 1, 53, 2),
    (60, 'Magneton', 4, 2, 'Formed by several Magnemites linked together. They frequently appear when sunspots flare up.', 'Sonicboom', '20', 'Fighting ×2', 'Metal -30', 1, 26, 2),
    (220, 'Pikachu V', 4, 7, 'This Pokemon has voltage-packed cheeks. It attacks while releasing electric shocks.', 'Thunder Shock', '20', 'Fighting ×2', NULL, 1, 43, 6),
    (310, 'Pikachu VMAX', 4, 8, 'Gigantamax energy upped the voltage in every one of Pikachus cells.', 'G-Max Volt Crash', '120+', 'Fighting ×2', NULL, 2, 44, 6),
    (190, 'Charizard V', 2, 7, 'It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.', 'Slash', '50', 'Water ×2', NULL, 2, 19, 6),
    (320, 'Charizard VMAX', 2, 8, 'The flame inside its body burns hotter than 3600 degrees Fahrenheit.', 'G-Max Wildfire', '100+', 'Water ×2', NULL, 3, 20, 6),
    (210, 'Mewtwo V', 5, 7, 'Its DNA is almost the same as Mews. However, its size and disposition are vastly different.', 'Psysplosion', '20×', 'Darkness ×2', NULL, 2, 30, 7),
    (180, 'Lucario ex', 6, 10, 'It controls waves known as auras, which are powerful enough to pulverize huge rocks.', 'Aura Sphere', '120', 'Psychic ×2', NULL, 2, 91, 7),
    (320, 'Miraidon ex', 4, 10, 'Much remains unknown about this creature. It resembles Cyclizar, but it is far more ruthless.', 'Photon Blaster', '220', 'Fighting ×2', NULL, 2, 81, 7),
    (220, 'Koraidon ex', 6, 10, 'This seems to be the Winged King mentioned in an old expedition journal. It was said to split the land.', 'Wild Impact', '220', 'Psychic ×2', NULL, 2, 80, 7),
    (70, 'Sprigatito', 1, 1, 'Its fluffy fur is similar in composition to plants. This Pokemon frequently washes its face to keep it from drying out.', 'Scratch', '10', 'Fire ×2', NULL, 1, 1, 7);
