INSERT INTO tbl_cards (hp, name, type_id, stage_id, info, attack, damage, weakness, resistance, retreat, cardNumberInCollection, collection_id) VALUES
    (50, 'Eevee', 11, 1, 'Thanks to its unstable genetic makeup, this special Pokemon conceals many different possible evolutions.', 'Tackle', '10', 'Fighting ×2', NULL, 1, 51, 1),
    (80, 'Vaporeon', 3, 2, 'Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaids.', 'Water Gun', '30+', 'Lightning ×2', NULL, 1, 12, 1),
    (80, 'Jolteon', 4, 2, 'It accumulates negative ions in the atmosphere to blast out 10000-volt lightning bolts.', 'Pin Missile', '20×', 'Fighting ×2', NULL, 1, 20, 1),
    (80, 'Flareon', 2, 2, 'When storing thermal energy in its body, its temperature could soar to over 1600 degrees.', 'Flare', '30', 'Water ×2', NULL, 1, 19, 1),
    (50, 'Vulpix', 2, 1, 'At the time of birth, it has just one tail. The tail splits from its tip as it grows older.', 'Confuse Ray', '10', 'Water ×2', NULL, 1, 68, 1),
    (80, 'Ninetales', 2, 2, 'Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.', 'Fire Blast', '80', 'Water ×2', NULL, 1, 38, 1),
    (50, 'Growlithe', 2, 1, 'Very protective of its territory. It will bark and bite to repel intruders from its space.', 'Flare', '20', 'Water ×2', NULL, 2, 28, 1),
    (100, 'Arcanine', 2, 2, 'A Pokemon that has been admired since the past for its beauty. It runs agilely as if on wings.', 'Take Down', '80', 'Water ×2', NULL, 3, 23, 1),
    (60, 'Ponyta', 2, 1, 'Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time.', 'Agility', '10', 'Water ×2', NULL, 1, 60, 1),
    (70, 'Rapidash', 2, 2, 'Very competitive, this Pokemon will chase anything that moves fast in the hopes of racing it.', 'Stomp', '40+', 'Water ×2', NULL, 0, 44, 1),
    (60, 'Magikarp', 3, 1, 'In the distant past, it was somewhat stronger than the horribly weak descendants that exist today.', 'Splash', '10', 'Lightning ×2', NULL, 1, 35, 3),
    (120, 'Gyarados', 3, 2, 'Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage.', 'Dragon Rage', '50', 'Lightning ×2', NULL, 3, 6, 3),
    (50, 'Dratini', 10, 1, 'Long considered a mythical Pokemon until recently when a small colony was found living underwater.', 'Wrap', '20', 'Fairy ×2', NULL, 1, 53, 3),
    (80, 'Dragonair', 10, 2, 'A mystical Pokemon that exudes a gentle aura. Has the ability to change climate conditions.', 'Slam', '30', 'Fairy ×2', NULL, 2, 18, 3),
    (120, 'Dragonite', 10, 3, 'An extremely rarely seen marine Pokemon. Its intelligence is said to match that of humans.', 'Hurricane', '40', 'Fairy ×2', NULL, 1, 19, 3),
    (60, 'Gastly', 5, 1, 'Almost invisible, this gaseous Pokemon cloaks the target and puts it to sleep without notice.', 'Lick', '10', 'Psychic ×2', 'Fighting -30', 1, 50, 3),
    (80, 'Haunter', 5, 2, 'Because of its ability to slip through block walls, it is said to be from another dimension.', 'Nightmare', '10', 'Psychic ×2', 'Fighting -30', 0, 21, 3),
    (120, 'Gengar', 5, 3, 'Under a full moon, this Pokemon likes to mimic the shadows of people and laugh at their fright.', 'Shadow Ball', '50', 'Psychic ×2', 'Fighting -30', 1, 20, 3),
    (70, 'Onix', 6, 1, 'As it grows, the stone portions of its body harden to become similar to a diamond, but colored black.', 'Rock Throw', '40', 'Grass ×2', NULL, 2, 56, 3),
    (60, 'Cubone', 6, 1, 'Because it never removes its skull helmet, no one has ever seen this Pokemons real face.', 'Bonemerang', '30×', 'Grass ×2', NULL, 1, 50, 3),
    (80, 'Marowak', 6, 2, 'The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets.', 'Bone Club', '60', 'Grass ×2', NULL, 1, 39, 3),
    (50, 'Hitmonlee', 6, 1, 'When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides.', 'Stretch Kick', '20', 'Psychic ×2', NULL, 1, 22, 4),
    (50, 'Hitmonchan', 6, 1, 'While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see.', 'Jab', '20', 'Psychic ×2', NULL, 2, 33, 4),
    (60, 'Koffing', 7, 1, 'Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.', 'Foul Gas', '10', 'Psychic ×2', NULL, 1, 51, 4),
    (90, 'Weezing', 7, 2, 'Where two kinds of poison gases meet, 2 Koffings can fuse into a Weezing over many years.', 'Smog', '20', 'Psychic ×2', NULL, 2, 45, 4),
    (40, 'Grimer', 7, 1, 'Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories.', 'Minimize', '10', 'Psychic ×2', NULL, 1, 48, 4),
    (80, 'Muk', 7, 2, 'Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison.', 'Sludge', '30', 'Psychic ×2', NULL, 2, 13, 4),
    (60, 'Ekans', 7, 1, 'Moves silently and stealthily. Eats the eggs of birds, such as Pidgey and Spearow, whole.', 'Spit Poison', '10', 'Psychic ×2', NULL, 1, 46, 4),
    (80, 'Arbok', 7, 2, 'It is rumored that the ferocious warning markings on its belly differ from area to area.', 'Poison Fang', '20', 'Psychic ×2', NULL, 1, 31, 4),
    (50, 'Sandshrew', 6, 1, 'Burrows deep underground in arid locations far from water. It only emerges to hunt for food.', 'Sand Attack', '10', 'Grass ×2', NULL, 1, 62, 4),
    (90, 'Sandslash', 6, 2, 'Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape.', 'Slash', '30', 'Grass ×2', NULL, 1, 41, 4),
    (220, 'Lugia V', 11, 7, 'It is said to be the guardian of the seas. It is rumored to have been seen on the night of a storm.', 'Aero Dive', '120', 'Lightning ×2', 'Fighting -30', 2, 138, 6),
    (190, 'Rayquaza V', 10, 7, 'It flies forever through the ozone layer, consuming meteoroids for sustenance.', 'Dragon Pulse', '120', 'Fairy ×2', NULL, 2, 110, 6),
    (280, 'Snorlax VMAX', 11, 8, 'Gigantamax energy has affected stray seeds and even pebbles that got stuck to Snorlax.', 'G-Max Replenish', '180', 'Fighting ×2', NULL, 4, 142, 6),
    (210, 'Gardevoir ex', 5, 10, 'To protect its Trainer, it will expend all its psychic power to create a small black hole.', 'Psychic', '60×', 'Metal ×2', NULL, 2, 86, 7);
