INSERT INTO tbl_cards (hp, name, type_id, stage_id, info, attack, damage, weakness, resistance, retreat, cardNumberInCollection, collection_id) VALUES
    (40, 'Zubat', 5, 1, 'Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.', 'Leech Life', '10', 'Lightning ×2', 'Fighting -30', 0, 57, 3),
    (70, 'Golbat', 5, 2, 'Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.', 'Wing Attack', '30', 'Lightning ×2', 'Fighting -30', 0, 34, 3),
    (50, 'Oddish', 1, 1, 'During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.', 'Absorb', '10', 'Fire ×2', NULL, 1, 43, 2),
    (80, 'Gloom', 1, 2, 'The fluid that oozes from its mouth isnt drool. It is a nectar that is used to attract prey.', 'Foul Odor', '20', 'Fire ×2', NULL, 1, 37, 2),
    (120, 'Vileplume', 1, 3, 'The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up.', 'Petal Dance', '70', 'Fire ×2', NULL, 2, 15, 2),
    (50, 'Paras', 1, 1, 'Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host.', 'Scratch', '10', 'Fire ×2', NULL, 1, 44, 2),
    (80, 'Parasect', 1, 2, 'A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places.', 'Spore', '20', 'Fire ×2', NULL, 1, 27, 2),
    (40, 'Venonat', 1, 1, 'Lives in the shadows of tall trees where it eats insects. It is attracted by light at night.', 'Stun Spore', '10', 'Fire ×2', NULL, 1, 41, 2),
    (70, 'Venomoth', 1, 2, 'The dust-like scales covering its wings are color coded to indicate the kinds of poison it has.', 'Poison Powder', '10', 'Fire ×2', NULL, 0, 13, 2),
    (60, 'Bellsprout', 1, 1, 'A carnivorous Pokemon that traps and eats bugs. It uses its root feet to soak up needed moisture.', 'Vine Whip', '10', 'Fire ×2', NULL, 1, 49, 2),
    (80, 'Weepinbell', 1, 2, 'It spits out poisonpowder to immobilize the enemy and then finishes it with a spray of acid.', 'Razor Leaf', '30', 'Fire ×2', NULL, 1, 48, 2),
    (100, 'Victreebel', 1, 3, 'Said to live in huge colonies deep in jungles, although no one has ever returned from there.', 'Acid', '40', 'Fire ×2', NULL, 2, 14, 2),
    (40, 'Tentacool', 3, 1, 'Drifts in shallow seas. Anglers who hook them by accident are often punished by their stingers.', 'Acid', '10', 'Lightning ×2', NULL, 0, 56, 2),
    (80, 'Tentacruel', 3, 2, 'The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.', 'Jellyfish Sting', '30', 'Lightning ×2', NULL, 0, 44, 2),
    (50, 'Seel', 3, 1, 'The protruding horn on its head is very hard. It is used for bashing through thick ice.', 'Headbutt', '10', 'Lightning ×2', NULL, 1, 41, 5),
    (90, 'Dewgong', 3, 2, 'Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters.', 'Aurora Beam', '50', 'Lightning ×2', NULL, 1, 25, 5),
    (60, 'Shellder', 3, 1, 'Its hard shell repels any kind of attack. It is vulnerable only when its shell is open.', 'Supersonic', '10', 'Lightning ×2', NULL, 1, 54, 5),
    (100, 'Cloyster', 3, 2, 'When attacked, it launches its horns in quick volleys. Its innards have never been seen.', 'Spike Cannon', '30×', 'Lightning ×2', NULL, 1, 32, 5),
    (40, 'Krabby', 3, 1, 'Its pincers are not only powerful weapons, they are used for balance when walking sideways.', 'Vice Grip', '20', 'Lightning ×2', NULL, 1, 51, 5),
    (80, 'Kingler', 3, 2, 'The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use.', 'Crabhammer', '60', 'Lightning ×2', NULL, 2, 38, 5);